/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowShowIdRouteImport } from './routes/show.$showId'
import { Route as ServicesProviderKeyRouteImport } from './routes/services_.$providerKey'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowShowIdRoute = ShowShowIdRouteImport.update({
  id: '/show/$showId',
  path: '/show/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProviderKeyRoute = ServicesProviderKeyRouteImport.update({
  id: '/services_/$providerKey',
  path: '/services/$providerKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/services/$providerKey': typeof ServicesProviderKeyRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/services/$providerKey': typeof ServicesProviderKeyRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/services_/$providerKey': typeof ServicesProviderKeyRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/services'
    | '/settings'
    | '/unauthorized'
    | '/services/$providerKey'
    | '/show/$showId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/services'
    | '/settings'
    | '/unauthorized'
    | '/services/$providerKey'
    | '/show/$showId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/services'
    | '/settings'
    | '/unauthorized'
    | '/services_/$providerKey'
    | '/show/$showId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ServicesProviderKeyRoute: typeof ServicesProviderKeyRoute
  ShowShowIdRoute: typeof ShowShowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$showId': {
      id: '/show/$showId'
      path: '/show/$showId'
      fullPath: '/show/$showId'
      preLoaderRoute: typeof ShowShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$providerKey': {
      id: '/services_/$providerKey'
      path: '/services/$providerKey'
      fullPath: '/services/$providerKey'
      preLoaderRoute: typeof ServicesProviderKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ServicesProviderKeyRoute: ServicesProviderKeyRoute,
  ShowShowIdRoute: ShowShowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
